const { StatusCodes } = require('http-status-codes');
const { User } = require('../../models');
const Auth = require('../../services/Auth');

class LoginController {
    /**
     *  @api {post} /auth/login Attempt to log
     *  @apiName PostAuthLogin
     *  @apiGroup Auth
     *  @apiVersion 1.0.0
     *
     *  @apiParam {String} email Users email
     *  @apiParam {String} password Users password
     *
     *  @apiParamExample {json} Request-Example:
     *     {
     *       "authToken": ""
     *       "email": "test@test.com"
     *       "password": "123456"
     *     }
     *
     *  @apiSuccessExample Success-Response:
     *     HTTP/1.1 200 OK
     *    {
     *        "auth": true,
     *        "token": TOKEN GENERATED BY JWT,
     *        "user": {
     *            "id": 6,
     *            "username": "aaaa",
     *            "firstName": "aaaaa",
     *            "lastName": "aaaaa",
     *            "email": "test@test.com"
     *        }
     *    }
     *
     *  @apiErrorExample Error-Response:
     *     HTTP/1.1 401 Unauthorized
     *     {
     *       "auth": false,
     *       "token": null,
     *        "user": null
     *     }
     */
    async invoke(request, response, next) {
        const { email, password } = request.body;

        const user = await User.findOne({
            where: { email },
            attributes: [
                'id',
                'userName',
                'firstName',
                'lastName',
                'email',
                'password'
            ]
        });

        if (!user) {
            return response
                .status(StatusCodes.UNAUTHORIZED)
                .json({ auth: false, token: null });
        }

        if (Auth.comparePasswords(password, user.getDataValue('password'))) {
            const token = Auth.signIn(user);
            let plainUser = user.get({ plain: true });
            delete plainUser.password;

            return response.json({ auth: true, token, user: plainUser });
        }

        return response
            .status(StatusCodes.UNAUTHORIZED)
            .json({ auth: false, token: null, user: null });
    }
}

module.exports = LoginController;
