version: '3'

volumes:
    postgres.data:

services:
    db:
        image: postgres
        container_name: ${COMPOSE_PROJECT_NAME}.postgres.docker
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - postgres.data:/var/lib/postgresql/data
        ports:
            - 127.0.0.1:${DATABASE_PORT}:5432
        networks:
            - global

networks:
    global:
        external: true
