const Auth = require('../services/Auth');
const { User } = require('../models');
const HttpStatus = require('http-status-codes');

class UserController {
    /**
     *  @api {get} /users Read all Users
     *  @apiName GetUserIndex
     *  @apiGroup Users
     *  @apiVersion 1.0.0
     *
     *  @apiSuccessExample Success-Response:
     *     HTTP/1.1 200 OK
     *    {
     *        "users": [
     *            {
     *                "id": 1,
     *                "userName": "uname",
     *                "firstName": "fname",
     *                "lastName": "lname",
     *                "email": "me@me1543244202844.com",
     *                "createdAt": "2018-11-26T14:56:43.003Z",
     *                "updatedAt": "2018-11-26T14:56:43.003Z"
     *            }
     *        ]
     *    }
     *
     *   @apiSuccess {Number}      id
     *   @apiSuccess {String}      userName
     *   @apiSuccess {String}      firstName
     *   @apiSuccess {String}      lastName
     *   @apiSuccess {String}      email
     *   @apiSuccess {Timestamp}   updatedAt
     *   @apiSuccess {Timestamp}   createdAt
     *
     *   @apiError (400) BadRequest
     */
    static getCollection(request, response, next) {
        User.findAll()
            .then(users => {
                response.json({ users });
            })
            .catch(next);
    }

    /**
     *  @api {post} /users Create User
     *  @apiName PostUserStore
     *  @apiGroup Users
     *  @apiVersion 1.0.0
     *
     *  @apiParam {String} userName
     *  @apiParam {String} firstName
     *  @apiParam {String} lastName
     *  @apiParam {String} email
     *  @apiParam {String} password
     *
     *  @apiParamExample {json} Request-Example:
     *   {
     *   	"userName": "aaaa",
     *   	"firstName": "aaaaa",
     *   	"lastName": "aaaaa",
     *   	"email": "test123@test.com",
     *   	"password": "123456"
     *   }
     *
     *  @apiSuccessExample Success-Response:
     *     HTTP/1.1 200 OK
     *    {
     *        "auth": true,
     *        "token": TOKEN GENERATED BY JWT,
     *        "user": {
     *            "id": 6,
     *            "userName": "aaaa",
     *            "firstName": "aaaaa",
     *            "lastName": "aaaaa",
     *            "updatedAt": "2018-11-27T11:57:02.003Z",
     *            "createdAt": "2018-11-27T11:57:02.003Z"
     *        }
     *    }
     *
     *  @apiSuccess {Boolean}    auth
     *  @apiSuccess {String}     token
     *  @apiSuccess {Object}     user
     *
     *  @apiError (400) BadRequest
     *
     */
    static async storeItem(request, response, next) {
        await User.create({ ...request.body })
            .then(user => {
                const token = Auth.signIn(user);

                let plainUser = user.get({ plain: true });
                delete plainUser.password;

                return response.json({ auth: true, token, user: plainUser });
            })
            .catch(next);
    }

    /**
     *  @api {get} /users/:id Show User
     *  @apiName GetUserShow
     *  @apiGroup Users
     *  @apiVersion 1.0.0
     *
     *  @apiParam {Number} id             ID of a User
     *
     *  @apiSuccessExample Success-Response:
     *     HTTP/1.1 200 OK
     *       OK
     *
     *   @apiError (404) Not Found    The User with <code>id</code> was not found.
     */
    static getItem(request, response, next) {
        const userId = request.params.id;

        User.findByPk(userId)
            .then(user => {
                if (!user) {
                    return response.sendStatus(HttpStatus.NOT_FOUND);
                }

                response.json(user);
            })
            .catch(next);
    }

    /**
     *  @api {put} /users Update User
     *  @apiName PutUserUpdate
     *  @apiGroup Users
     *  @apiVersion 1.0.0
     *
     *  @apiParam {String} userName
     *  @apiParam {String} firstName
     *  @apiParam {String} lastName
     *  @apiParam {String} email User
     *  @apiParam {String} password
     *
     *  @apiParamExample {json} Request-Example:
     *   {
     *   	"userName": "aaaa",
     *   	"firstName": "aaaaa",
     *   	"lastName": "aaaaa",
     *   	"email": "test123@test.com",
     *   	"password": "123456"
     *   }
     *
     *  @apiSuccessExample Success-Response:
     *     HTTP/1.1 200 OK
     *    {
     *        "auth": true,
     *        "token": TOKEN GENERATED BY JWT,
     *        "user": {
     *            "id": 6,
     *            "userName": "aaaa",
     *            "firstName": "aaaaa",
     *            "lastName": "aaaaa",
     *            "updatedAt": "2018-11-27T11:57:02.003Z",
     *            "createdAt": "2018-11-27T11:57:02.003Z"
     *        }
     *    }
     *
     *  @apiSuccess {Boolean}    auth
     *  @apiSuccess {String}     token
     *  @apiSuccess {Object}     user
     *
     *   @apiError NotFound     The User with <code>id</code> was not found.
     *   @apiError Forbidden    Users can delete only themselfs
     *   @apiError BadRequest
     *
     */
    static putItem(request, response, next) {
        const userId = request.params.id;
        const fields = request.body;

        User.findByPk(userId).then(user => {
            if (!user) {
                return response.sendStatus(HttpStatus.NOT_FOUND);
            }

            if (user.id !== request.loggedUserId) {
                return response.sendStatus(HttpStatus.FORBIDDEN);
            }

            user.update(fields)
                .then(() => {
                    response.sendStatus(HttpStatus.OK);
                })
                .catch(next);
        });
    }

    /**
     *  @api {delete} /users/:id Delete User
     *  @apiName DeleteUserDestroy
     *  @apiGroup Users
     *  @apiVersion 1.0.0
     *
     *  @apiParam {Number} id             ID of a ToDo List element
     *
     *  @apiSuccessExample Success-Response:
     *     HTTP/1.1 204 No Content
     *
     *   @apiError NotFound     The User with <code>id</code> was not found.
     *   @apiError Forbidden    Users can delete only themselfs
     *   @apiError BadRequest
     */
    static destroyItem(request, response, next) {
        const userId = request.params.id;

        User.findByPk(request.params.id).then(user => {
            if (!user) {
                return response.sendStatus(HttpStatus.NOT_FOUND);
            }

            if (user.id !== request.loggedUserId) {
                return response.sendStatus(HttpStatus.FORBIDDEN);
            }

            user.destroy()
                .then(() => {
                    response.sendStatus(HttpStatus.NO_CONTENT);
                })
                .catch(next);
        });
    }
}

module.exports = UserController;
